# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 1

name: $(major).$(minor)$(Rev:.r)


steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: testAssemblies
    testAssemblyVer2: |
      **\*test.unit*.dll
      !**\*TestAdapter.dll
      !**\obj\** 
    codeCoverageEnabled: true
    runSettingsFile: AzTestReporter\CodeCoverage.runsettings

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      tree /a /f

      Write-Host "Generating report"      
      .\AzTestReporter\publish\Bin\Release\AnyCPU\AzTestReporter.App\net472\AzTestReporter.exe --trt Unit --sendmail false -f HTML -o $(SYSTEM_DEFAULTWORKINGDIRECTORY)\Report
    errorActionPreference: 'continue'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    condition: always()

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.\AzTestReporter\publish\Bin\$(buildConfiguration)\AnyCPU\AzTestReporter.App\net472'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.\AzTestReporter\publish\Bin\$(buildConfiguration)\AnyCPU\AzTestReporter.App\aztestreporter.$(Build.BuildNumber).nupkg'
    ArtifactName: 'nugetpkg'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(SYSTEM_DEFAULTWORKINGDIRECTORY)\Report'
    ArtifactName: 'report'
    publishLocation: 'Container'
    condition: always()